### ISSUE TITLE
Time ago since event occurred not displaying in feed

### ISSUE THREAD

**Issue by grdryn** [e14n/openfarmgame#38]
In my feed, when something happens like a crop needing water, there's no indication how long ago since the notification came.

Right now I see:
 Open Farm Game at To: You

where it's probably expected to be more like:
 Open Farm Game at _1 hour ago_ To: You

**Comment by evanp** [comment]
Good point! I wonder why it's doing that?

**Comment by grdryn** [comment]
I'm looking around to see if I can figure it out, but I don't yet know enough about any of the code. :)

<a href="https://openfarmgame.com/">Open Farm Game</a> at 
        <a href=""><abbr title="" class="easydate"></abbr></a>

compared to 

<a href="https://e14n.com/evan">Evan Prodromou</a> at 
        <a href="https://e14n.com/evan/note/c_hvQsH2QA6DrTgFdnaX1w"><abbr title="2013-03-30T01:59:14Z" class="easydate">16 hours ago</abbr></a>

Is that data sent by openfarmgame to the pump.io server that the user has an account on, or is it generated by the pump server when it receives the notification?

**Comment by grdryn** [comment]
Eugh, I pasted html there which won't work. The [...] compared to [...] part of that previous comment should look more like this: http://fpaste.org/fD37/

**Comment by grdryn** [comment]
Works! Nice job, thanks! :)

**Comment by evanp** [comment]
Cool, glad this worked.
